import { I18nManager, StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    maxHeight: "100%",
    direction: "rtl",
  },
  buttonsContainer: {
    display: "flex",
    flexDirection: "row",
    padding: 10,
    paddingBottom: 0,
    gap: 10,
    direction: "rtl",
  },
  button: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    // padding: 13,
    backgroundColor: "#fff",
    textAlign: "center",
    borderColor: "#f7f7f7",
    borderWidth: 1,
    height: 45,
  },
  buttonText: {
    textAlign: "center",
    color: "grey",
    fontSize: 12,
    fontFamily: "CairoBold",
  },
  active: {
    borderColor: "#A91101",
    backgroundColor: "#fff",
    color: "#A91101",
  },
  controlsContainers: {
    padding: 20,
    backgroundColor: "#a9110121",
    margin: 10,
    marginTop: 15,
    borderRadius: 10,
  },
  numbers: {
    display: "flex",
    direction: "rtl",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 30,
  },
  number: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  numberText: {
    textAlign: "right",
    fontFamily: "CairoBold",
    fontSize: 13,
  },
  controls: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 0,
    direction: "rtl",
  },
  buttonContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  icon: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "#A91101",
    width: 35,
    height: 35,
    borderRadius: "50%",
  },
  btnText: {
    fontFamily: "Cairo",
    fontSize: 12,
    width: 40,
    lineHeight: 15,
  },
  statistics: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    direction: "rtl",
    padding: 10,
    paddingTop: 5,
  },
  item: {
    position: "relative",
    // backgroundColor: "#fff",
    borderColor: "#f7f7f7",
    borderWidth: 1,
    width: "31.5%",
    paddingVertical: 16,
    // aspectRatio: 1, // Square shape
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    // borderRadius: 6,
    direction: "rtl",
    borderRadius: 10,
    shadowColor: "#ccc",
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 12, // for Android
  },

  statusIcon: {
    position: "absolute",
    [I18nManager.isRTL ? "left" : "right"]: 5,
    top: 5,
    width: 20,
    height: 20,
  },
  statusCount: {
    marginBottom: 5,
    fontSize: 12,
  },
  statusName: {
    flexDirection: "row",
  },
  statusNameText: {
    fontFamily: "CairoBold",
    fontSize: 7,
  },
  navbar: {
    position: "absolute",
    width: "100%",
    padding: 10,
    zIndex: 11100,
    flexDirection: "row",
    justifyContent: "space-between",
    direction: "rtl",
  },
  navbarItem: {
    flexDirection: "row",
    direction: "ltr",
  },
  bell: {
    position: "relative",
    width: 35,
  },
  bellNumber: {
    position: "absolute",
    top: -10,
    left: 8,
    zIndex: 555,
    width: 20,
    height: 20,
    fontSize: 10,
    paddingTop: 3,
    backgroundColor: "red",
    color: "#FFF",
    textAlign: "center",
    borderRadius: 10,
  },
  floatingButton: {
    position: "absolute",
    bottom: 20,
    [!I18nManager.isRTL ? "left" : "right"]: 10,
    backgroundColor: "#A91101",
    padding: 12,
    borderRadius: 30,
    elevation: 5, // for Android shadow
    shadowColor: "#000", // for iOS shadow
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    direction: "rtl",
  },
  totalUnseen: {
    position: "absolute",
    width: 20,
    height: 20,
    backgroundColor: "red",
    color: "#fff",
    borderRadius: 10,
    zIndex: 555,
    fontSize: 10,
    paddingTop: 3,
    textAlign: "center",
    left: 3,
    top: -8,
  },
  searchContainer: {
    position: "absolute",
    flex: 1,
    margin: 10,
    padding: 10,
    zIndex: 11100,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  searchInput: {
    flex: 1,
    height: 40,
    color: "grey",
    fontSize: 16,
  },
});
export default styles;
